export const Productos = [
  { id: 1, nombre: 'Computadora Hp', precio: 1100, country: "Germany" },
  { id: 2, nombre: 'Computadora Dell', precio: 1200, country: "United States" },
  { id: 3, nombre: 'Computadora Lenovo', precio: 1300, country: "Brazil" },
  { id: 4, nombre: 'Computadora Asus', precio: 1400, country: "Canada" },
  { id: 5, nombre: 'Computadora Apple', precio: 1500, country: "France" },
  { id: 6, nombre: 'Computadora Samsung', precio: 1600, country: "RU" },
  { id: 7, nombre: 'Computadora Acer', precio: 1700, country: "Guatemala" },
  { id: 8, nombre: 'Computadora Toshiba', precio: 1800, country: "Germany" },
  { id: 9, nombre: 'Computadora Sony', precio: 1900, country: "United States" },
  { id: 10, nombre: 'Computadora Huawei', precio: 2000, country: "Brazil" },
  { id: 11, nombre: 'Computadora LG', precio: 2100, country: "Canada" },
  { id: 12, nombre: 'Computadora Xiaomi', precio: 2200, country: "France" },
  { id: 13, nombre: 'Computadora Motorola', precio: 2300, country: "RU" },
  { id: 14, nombre: 'Computadora Nokia', precio: 2400, country: "Guatemala" },
  { id: 15, nombre: 'Computadora Alcatel', precio: 2500, country: "Germany" },
  { id: 16, nombre: 'Computadora HTC', precio: 2600, country: "United States" },
  { id: 17, nombre: 'Computadora Oppo', precio: 2700, country: "Brazil" },
  { id: 18, nombre: 'Computadora ZTE', precio: 2800, country: "Canada" },
  { id: 19, nombre: 'Computadora One Plus', precio: 2900, country: "France" },
  { id: 20, nombre: 'Computadora One Zero', precio: 4000, country: "RU" },
];